using JuMP
using SCIP

MIN_PRODUCTION_QUANTITY = 5

STEEL_PRICE = 3
METAL_PRICE = 6

MAX_STEEL_PRODUCTION = 4
MAX_METAL_PRODUCTION = 7

MAX_METAL_PER_STEEL = 7/8

AVAILABLE_TIME = 18
STEEL_PRODUCTION_TIME = 3
METAL_PRODUCTION_TIME = 2

model = Model(SCIP.Optimizer)

@variable(model, STEEL_QUANTITY <= MAX_STEEL_PRODUCTION)
@variable(model, METAL_QUANTITY <= MAX_METAL_PRODUCTION)

@objective(model, Min, STEEL_PRICE*STEEL_QUANTITY + METAL_PRICE*METAL_QUANTITY)

@constraint(model, STEEL_PRODUCTION_TIME*STEEL_QUANTITY + METAL_PRODUCTION_TIME*METAL_QUANTITY <= AVAILABLE_TIME)

@constraint(model, METAL_QUANTITY + STEEL_QUANTITY >= MIN_PRODUCTION_QUANTITY)

@constraint(model, METAL_QUANTITY <= MAX_METAL_PER_STEEL * STEEL_QUANTITY)

# Find solution
optimize!(model)
@show objective_value(model)
@show value(STEEL_QUANTITY) value(METAL_QUANTITY)